- name: Test AWS playbook
  hosts: local
  connection: local
  tasks:
    - name: Get VPCs
      amazon.aws.ec2_vpc_net_info:
        region: ap-southeast-2
      register: vpc_info

    - name: Simple debug output
      debug:
        msg: "{{ vpc_info }}"
